name: assignment01
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_image: ^4.1.7
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/animation.gif  # ✅ Use forward slashes `/` instead of backslashes `\`
